# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: "sqla"
    replace: "sqlalchemy"

  

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  # ========================= STIANS FILER =========================

  ## eksempel på REGEX
  #- regex: "greet(?P<person>.*),(?P<dude>.*)\\."
  #  replace: "Hi {{person}} and {{dude}}!"


  # MAILS
  

  
  # ================================================== DEVELOPMENT ==================================================

 
  #  HTML 
  
  - trigger: ":div"
    replace: '<div class="$|$></div>'


  - trigger: "def"
    replace: "def $|$():"


# PYTHON

  - trigger: ":one"
    replace: "nested"

  - trigger: ":nested"
    replace: "This is a {{output}} match"
    vars:
      - name: output
        type: match
        params:
          trigger: ":one"

##################################################
#                    Diverse                     #
##################################################

  - trigger: ":lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Donec sed odio operae, eu vulputate felis rhoncus. Salutantibus vitae elit libero, a pharetra augue. Nihil hic munitissimus habendi senatus locus, nihil horum? A communi observantia non est recedendum."


##################################################
#                    OBSIDAN                     #
##################################################


#######################
#         UIT         #
#######################

  - trigger: ":uit"
    replace: "❄️UIT"

#### 1 Semester ###
  - trigger: ":1sem"
    replace: "❄️UIT, ❄️UIT/1-semester"

# Fag 
  - trigger: ":tek1509"
    replace: "❄️UIT, ❄️UIT/1-semester/TEK-1509-Teknisk-Realfag(Forkurs-Matte/Fysikk)"
  - trigger: ":tek1502"
    replace: "❄️UIT, ❄️UIT/1-semester/TEK-1502-Ingeniørfaglig-Metode"
  - trigger: ":tek1508"
    replace: "❄️UIT, ❄️UIT/1-semester/TEK-1508-Teknisk-Språkføring-Norsk"
  - trigger: ":tek1506"
    replace: "❄️UIT, ❄️UIT/1-semester/TEK-1506-Teknisk-Tegning/DAK"    


#### 1 Semester ###

  - trigger: ":2sem"
    replace: "❄️UIT, ❄️UIT/2-semester"

# Fag

  - trigger: ":byg2503"
    replace: "❄️UIT, ❄️UIT/2-semester/BYG-2503-Mekanikk-og-Fluidmekanikk"
  - trigger: ":tek1504"
    replace: "❄️UIT, ❄️UIT/2-semester/TEK-1504-Fysikk"
  - trigger: ":tek1505"
    replace: "❄️UIT, ❄️UIT/2-semester/TEK-1505-Kjemi"
  - trigger: ":tek1508"
    replace: "❄️UIT, ❄️UIT/2-semester/TEK-1508-Teknisk-Språkføring-Engelsk"

# Fag
  - trigger: ":3sem"
    replace: "❄️UIT, ❄️UIT/3-semester"

# Fag
  - trigger: ":tek1507"
    replace: "❄️UIT, ❄️UIT/3-semester/TEK-1507-Matematikk-1"
  - trigger: ":byg2602"
    replace: "❄️UIT, ❄️UIT/3-semester/BYG-2602-Statikk/Dynamikk-og-Konstruksjonslære"
  - trigger: ":byg2502"
    replace: "❄️UIT, ❄️UIT/3-semester/BYG-2502-Grunnleggende-byggfag"
  - trigger: ":dte2510"
    replace: "❄️UIT, ❄️UIT/3-semester/DTE-2510-Grunnleggende-programmering"



# 4 Semester
  - trigger: ":4sem"
    replace: "❄️UIT, ❄️UIT/4-semester"

# Fag
  - trigger: ":dte2509"
    replace: "❄️UIT, ❄️UIT/4-semester/DTE-2509-Databaser-og-webapplikasjoner-1"
  - trigger: ":dte2511"
    replace: "❄️UIT, ❄️UIT/4-semester/DTE-2511-Videregående-programmering"
  - trigger: ":dte2604"
    replace: "❄️UIT, ❄️UIT/4-semester/DTE-2604-Systemutvikling"
  - trigger: ":tek1516"
    replace: "❄️UIT, ❄️UIT/4-semester/TEK-1516-Matematikk-2"


# 5 Semester
  - trigger: ":5sem"
    replace: "❄️UIT, ❄️UIT/5-semester"

# 6 Semester
  - trigger: ":6sem"
    replace: "❄️UIT, ❄️UIT/6-semester"

  #

  - trigger: ":moc"
    replace: "🧠MOC"

  - trigger: ":day"
    replace: "📓daily-note"

  - trigger: ":ide"
    replace: "💡ide"

  - trigger: ":inb"
    replace: "📥inbox"

  - trigger: ":awe"
    replace: "🤑awesome"

  - trigger: ":doku"
    replace: "📑dokumentasjon"

  - trigger: ":pyt"
    replace: "🐍python"

  - trigger: ":snip"
    replace: "✂️snippets"
  
  - trigger: ":pysni"
    replace: "🐍python, ✂️snippets/🐍python, 🐍python/✂️snippets"

  - trigger: ":che"
    replace: "🤠cheatsheet"

  - trigger: ":dev"
    replace: "🔧dev"

  - trigger: ":virus"
    replace: "🦠"

  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""
  #- trigger: ":"
  #  replace: ""